import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../shared/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["hello"]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          {isLoading ? "Loading..." : data?.greeting}
        </h1>
      </main>
    </div>
  );
};

export default Home;
